name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQubeScan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run SonarQube analysis
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          projectKey: 'com.miempresa.miproyecto'  # Cambia esto con tu projectKey
          organization: 'tu_organizacion'       # Cambia esto con tu organización
          sonar-host-url: 'http://localhost:9000'  # Asegúrate de que sea tu URL de SonarQube

      - name: Build with Maven
        run: mvn clean install
